# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pichurria/dev-pichurria/cocos2d-pichurriajuegos/projects/moreneuron

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pichurria/dev-pichurria/cocos2d-pichurriajuegos/projects/moreneuron

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pichurria/dev-pichurria/cocos2d-pichurriajuegos/projects/moreneuron/CMakeFiles /home/pichurria/dev-pichurria/cocos2d-pichurriajuegos/projects/moreneuron/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pichurria/dev-pichurria/cocos2d-pichurriajuegos/projects/moreneuron/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MoreNeuron

# Build rule for target.
MoreNeuron: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MoreNeuron
.PHONY : MoreNeuron

# fast build rule for target.
MoreNeuron/fast:
	$(MAKE) -f CMakeFiles/MoreNeuron.dir/build.make CMakeFiles/MoreNeuron.dir/build
.PHONY : MoreNeuron/fast

#=============================================================================
# Target rules for targets named MoreNeuron_CORE_PRE_BUILD

# Build rule for target.
MoreNeuron_CORE_PRE_BUILD: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MoreNeuron_CORE_PRE_BUILD
.PHONY : MoreNeuron_CORE_PRE_BUILD

# fast build rule for target.
MoreNeuron_CORE_PRE_BUILD/fast:
	$(MAKE) -f CMakeFiles/MoreNeuron_CORE_PRE_BUILD.dir/build.make CMakeFiles/MoreNeuron_CORE_PRE_BUILD.dir/build
.PHONY : MoreNeuron_CORE_PRE_BUILD/fast

#=============================================================================
# Target rules for targets named MoreNeuron_PRE_BUILD

# Build rule for target.
MoreNeuron_PRE_BUILD: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MoreNeuron_PRE_BUILD
.PHONY : MoreNeuron_PRE_BUILD

# fast build rule for target.
MoreNeuron_PRE_BUILD/fast:
	$(MAKE) -f CMakeFiles/MoreNeuron_PRE_BUILD.dir/build.make CMakeFiles/MoreNeuron_PRE_BUILD.dir/build
.PHONY : MoreNeuron_PRE_BUILD/fast

Classes/AppDelegate.o: Classes/AppDelegate.cpp.o
.PHONY : Classes/AppDelegate.o

# target to build an object file
Classes/AppDelegate.cpp.o:
	$(MAKE) -f CMakeFiles/MoreNeuron.dir/build.make CMakeFiles/MoreNeuron.dir/Classes/AppDelegate.cpp.o
.PHONY : Classes/AppDelegate.cpp.o

Classes/AppDelegate.i: Classes/AppDelegate.cpp.i
.PHONY : Classes/AppDelegate.i

# target to preprocess a source file
Classes/AppDelegate.cpp.i:
	$(MAKE) -f CMakeFiles/MoreNeuron.dir/build.make CMakeFiles/MoreNeuron.dir/Classes/AppDelegate.cpp.i
.PHONY : Classes/AppDelegate.cpp.i

Classes/AppDelegate.s: Classes/AppDelegate.cpp.s
.PHONY : Classes/AppDelegate.s

# target to generate assembly for a file
Classes/AppDelegate.cpp.s:
	$(MAKE) -f CMakeFiles/MoreNeuron.dir/build.make CMakeFiles/MoreNeuron.dir/Classes/AppDelegate.cpp.s
.PHONY : Classes/AppDelegate.cpp.s

Classes/Crux.o: Classes/Crux.cpp.o
.PHONY : Classes/Crux.o

# target to build an object file
Classes/Crux.cpp.o:
	$(MAKE) -f CMakeFiles/MoreNeuron.dir/build.make CMakeFiles/MoreNeuron.dir/Classes/Crux.cpp.o
.PHONY : Classes/Crux.cpp.o

Classes/Crux.i: Classes/Crux.cpp.i
.PHONY : Classes/Crux.i

# target to preprocess a source file
Classes/Crux.cpp.i:
	$(MAKE) -f CMakeFiles/MoreNeuron.dir/build.make CMakeFiles/MoreNeuron.dir/Classes/Crux.cpp.i
.PHONY : Classes/Crux.cpp.i

Classes/Crux.s: Classes/Crux.cpp.s
.PHONY : Classes/Crux.s

# target to generate assembly for a file
Classes/Crux.cpp.s:
	$(MAKE) -f CMakeFiles/MoreNeuron.dir/build.make CMakeFiles/MoreNeuron.dir/Classes/Crux.cpp.s
.PHONY : Classes/Crux.cpp.s

Classes/CruxBoard.o: Classes/CruxBoard.cpp.o
.PHONY : Classes/CruxBoard.o

# target to build an object file
Classes/CruxBoard.cpp.o:
	$(MAKE) -f CMakeFiles/MoreNeuron.dir/build.make CMakeFiles/MoreNeuron.dir/Classes/CruxBoard.cpp.o
.PHONY : Classes/CruxBoard.cpp.o

Classes/CruxBoard.i: Classes/CruxBoard.cpp.i
.PHONY : Classes/CruxBoard.i

# target to preprocess a source file
Classes/CruxBoard.cpp.i:
	$(MAKE) -f CMakeFiles/MoreNeuron.dir/build.make CMakeFiles/MoreNeuron.dir/Classes/CruxBoard.cpp.i
.PHONY : Classes/CruxBoard.cpp.i

Classes/CruxBoard.s: Classes/CruxBoard.cpp.s
.PHONY : Classes/CruxBoard.s

# target to generate assembly for a file
Classes/CruxBoard.cpp.s:
	$(MAKE) -f CMakeFiles/MoreNeuron.dir/build.make CMakeFiles/MoreNeuron.dir/Classes/CruxBoard.cpp.s
.PHONY : Classes/CruxBoard.cpp.s

Classes/GameOverScene.o: Classes/GameOverScene.cpp.o
.PHONY : Classes/GameOverScene.o

# target to build an object file
Classes/GameOverScene.cpp.o:
	$(MAKE) -f CMakeFiles/MoreNeuron.dir/build.make CMakeFiles/MoreNeuron.dir/Classes/GameOverScene.cpp.o
.PHONY : Classes/GameOverScene.cpp.o

Classes/GameOverScene.i: Classes/GameOverScene.cpp.i
.PHONY : Classes/GameOverScene.i

# target to preprocess a source file
Classes/GameOverScene.cpp.i:
	$(MAKE) -f CMakeFiles/MoreNeuron.dir/build.make CMakeFiles/MoreNeuron.dir/Classes/GameOverScene.cpp.i
.PHONY : Classes/GameOverScene.cpp.i

Classes/GameOverScene.s: Classes/GameOverScene.cpp.s
.PHONY : Classes/GameOverScene.s

# target to generate assembly for a file
Classes/GameOverScene.cpp.s:
	$(MAKE) -f CMakeFiles/MoreNeuron.dir/build.make CMakeFiles/MoreNeuron.dir/Classes/GameOverScene.cpp.s
.PHONY : Classes/GameOverScene.cpp.s

Classes/HelpScene.o: Classes/HelpScene.cpp.o
.PHONY : Classes/HelpScene.o

# target to build an object file
Classes/HelpScene.cpp.o:
	$(MAKE) -f CMakeFiles/MoreNeuron.dir/build.make CMakeFiles/MoreNeuron.dir/Classes/HelpScene.cpp.o
.PHONY : Classes/HelpScene.cpp.o

Classes/HelpScene.i: Classes/HelpScene.cpp.i
.PHONY : Classes/HelpScene.i

# target to preprocess a source file
Classes/HelpScene.cpp.i:
	$(MAKE) -f CMakeFiles/MoreNeuron.dir/build.make CMakeFiles/MoreNeuron.dir/Classes/HelpScene.cpp.i
.PHONY : Classes/HelpScene.cpp.i

Classes/HelpScene.s: Classes/HelpScene.cpp.s
.PHONY : Classes/HelpScene.s

# target to generate assembly for a file
Classes/HelpScene.cpp.s:
	$(MAKE) -f CMakeFiles/MoreNeuron.dir/build.make CMakeFiles/MoreNeuron.dir/Classes/HelpScene.cpp.s
.PHONY : Classes/HelpScene.cpp.s

Classes/MoreNeuronBG.o: Classes/MoreNeuronBG.cpp.o
.PHONY : Classes/MoreNeuronBG.o

# target to build an object file
Classes/MoreNeuronBG.cpp.o:
	$(MAKE) -f CMakeFiles/MoreNeuron.dir/build.make CMakeFiles/MoreNeuron.dir/Classes/MoreNeuronBG.cpp.o
.PHONY : Classes/MoreNeuronBG.cpp.o

Classes/MoreNeuronBG.i: Classes/MoreNeuronBG.cpp.i
.PHONY : Classes/MoreNeuronBG.i

# target to preprocess a source file
Classes/MoreNeuronBG.cpp.i:
	$(MAKE) -f CMakeFiles/MoreNeuron.dir/build.make CMakeFiles/MoreNeuron.dir/Classes/MoreNeuronBG.cpp.i
.PHONY : Classes/MoreNeuronBG.cpp.i

Classes/MoreNeuronBG.s: Classes/MoreNeuronBG.cpp.s
.PHONY : Classes/MoreNeuronBG.s

# target to generate assembly for a file
Classes/MoreNeuronBG.cpp.s:
	$(MAKE) -f CMakeFiles/MoreNeuron.dir/build.make CMakeFiles/MoreNeuron.dir/Classes/MoreNeuronBG.cpp.s
.PHONY : Classes/MoreNeuronBG.cpp.s

Classes/MoreNeuronScene.o: Classes/MoreNeuronScene.cpp.o
.PHONY : Classes/MoreNeuronScene.o

# target to build an object file
Classes/MoreNeuronScene.cpp.o:
	$(MAKE) -f CMakeFiles/MoreNeuron.dir/build.make CMakeFiles/MoreNeuron.dir/Classes/MoreNeuronScene.cpp.o
.PHONY : Classes/MoreNeuronScene.cpp.o

Classes/MoreNeuronScene.i: Classes/MoreNeuronScene.cpp.i
.PHONY : Classes/MoreNeuronScene.i

# target to preprocess a source file
Classes/MoreNeuronScene.cpp.i:
	$(MAKE) -f CMakeFiles/MoreNeuron.dir/build.make CMakeFiles/MoreNeuron.dir/Classes/MoreNeuronScene.cpp.i
.PHONY : Classes/MoreNeuronScene.cpp.i

Classes/MoreNeuronScene.s: Classes/MoreNeuronScene.cpp.s
.PHONY : Classes/MoreNeuronScene.s

# target to generate assembly for a file
Classes/MoreNeuronScene.cpp.s:
	$(MAKE) -f CMakeFiles/MoreNeuron.dir/build.make CMakeFiles/MoreNeuron.dir/Classes/MoreNeuronScene.cpp.s
.PHONY : Classes/MoreNeuronScene.cpp.s

Classes/NeuronMenuScene.o: Classes/NeuronMenuScene.cpp.o
.PHONY : Classes/NeuronMenuScene.o

# target to build an object file
Classes/NeuronMenuScene.cpp.o:
	$(MAKE) -f CMakeFiles/MoreNeuron.dir/build.make CMakeFiles/MoreNeuron.dir/Classes/NeuronMenuScene.cpp.o
.PHONY : Classes/NeuronMenuScene.cpp.o

Classes/NeuronMenuScene.i: Classes/NeuronMenuScene.cpp.i
.PHONY : Classes/NeuronMenuScene.i

# target to preprocess a source file
Classes/NeuronMenuScene.cpp.i:
	$(MAKE) -f CMakeFiles/MoreNeuron.dir/build.make CMakeFiles/MoreNeuron.dir/Classes/NeuronMenuScene.cpp.i
.PHONY : Classes/NeuronMenuScene.cpp.i

Classes/NeuronMenuScene.s: Classes/NeuronMenuScene.cpp.s
.PHONY : Classes/NeuronMenuScene.s

# target to generate assembly for a file
Classes/NeuronMenuScene.cpp.s:
	$(MAKE) -f CMakeFiles/MoreNeuron.dir/build.make CMakeFiles/MoreNeuron.dir/Classes/NeuronMenuScene.cpp.s
.PHONY : Classes/NeuronMenuScene.cpp.s

Classes/PresentationScene.o: Classes/PresentationScene.cpp.o
.PHONY : Classes/PresentationScene.o

# target to build an object file
Classes/PresentationScene.cpp.o:
	$(MAKE) -f CMakeFiles/MoreNeuron.dir/build.make CMakeFiles/MoreNeuron.dir/Classes/PresentationScene.cpp.o
.PHONY : Classes/PresentationScene.cpp.o

Classes/PresentationScene.i: Classes/PresentationScene.cpp.i
.PHONY : Classes/PresentationScene.i

# target to preprocess a source file
Classes/PresentationScene.cpp.i:
	$(MAKE) -f CMakeFiles/MoreNeuron.dir/build.make CMakeFiles/MoreNeuron.dir/Classes/PresentationScene.cpp.i
.PHONY : Classes/PresentationScene.cpp.i

Classes/PresentationScene.s: Classes/PresentationScene.cpp.s
.PHONY : Classes/PresentationScene.s

# target to generate assembly for a file
Classes/PresentationScene.cpp.s:
	$(MAKE) -f CMakeFiles/MoreNeuron.dir/build.make CMakeFiles/MoreNeuron.dir/Classes/PresentationScene.cpp.s
.PHONY : Classes/PresentationScene.cpp.s

Classes/TextInput.o: Classes/TextInput.cpp.o
.PHONY : Classes/TextInput.o

# target to build an object file
Classes/TextInput.cpp.o:
	$(MAKE) -f CMakeFiles/MoreNeuron.dir/build.make CMakeFiles/MoreNeuron.dir/Classes/TextInput.cpp.o
.PHONY : Classes/TextInput.cpp.o

Classes/TextInput.i: Classes/TextInput.cpp.i
.PHONY : Classes/TextInput.i

# target to preprocess a source file
Classes/TextInput.cpp.i:
	$(MAKE) -f CMakeFiles/MoreNeuron.dir/build.make CMakeFiles/MoreNeuron.dir/Classes/TextInput.cpp.i
.PHONY : Classes/TextInput.cpp.i

Classes/TextInput.s: Classes/TextInput.cpp.s
.PHONY : Classes/TextInput.s

# target to generate assembly for a file
Classes/TextInput.cpp.s:
	$(MAKE) -f CMakeFiles/MoreNeuron.dir/build.make CMakeFiles/MoreNeuron.dir/Classes/TextInput.cpp.s
.PHONY : Classes/TextInput.cpp.s

proj.linux/main.o: proj.linux/main.cpp.o
.PHONY : proj.linux/main.o

# target to build an object file
proj.linux/main.cpp.o:
	$(MAKE) -f CMakeFiles/MoreNeuron.dir/build.make CMakeFiles/MoreNeuron.dir/proj.linux/main.cpp.o
.PHONY : proj.linux/main.cpp.o

proj.linux/main.i: proj.linux/main.cpp.i
.PHONY : proj.linux/main.i

# target to preprocess a source file
proj.linux/main.cpp.i:
	$(MAKE) -f CMakeFiles/MoreNeuron.dir/build.make CMakeFiles/MoreNeuron.dir/proj.linux/main.cpp.i
.PHONY : proj.linux/main.cpp.i

proj.linux/main.s: proj.linux/main.cpp.s
.PHONY : proj.linux/main.s

# target to generate assembly for a file
proj.linux/main.cpp.s:
	$(MAKE) -f CMakeFiles/MoreNeuron.dir/build.make CMakeFiles/MoreNeuron.dir/proj.linux/main.cpp.s
.PHONY : proj.linux/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... MoreNeuron"
	@echo "... MoreNeuron_CORE_PRE_BUILD"
	@echo "... MoreNeuron_PRE_BUILD"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Classes/AppDelegate.o"
	@echo "... Classes/AppDelegate.i"
	@echo "... Classes/AppDelegate.s"
	@echo "... Classes/Crux.o"
	@echo "... Classes/Crux.i"
	@echo "... Classes/Crux.s"
	@echo "... Classes/CruxBoard.o"
	@echo "... Classes/CruxBoard.i"
	@echo "... Classes/CruxBoard.s"
	@echo "... Classes/GameOverScene.o"
	@echo "... Classes/GameOverScene.i"
	@echo "... Classes/GameOverScene.s"
	@echo "... Classes/HelpScene.o"
	@echo "... Classes/HelpScene.i"
	@echo "... Classes/HelpScene.s"
	@echo "... Classes/MoreNeuronBG.o"
	@echo "... Classes/MoreNeuronBG.i"
	@echo "... Classes/MoreNeuronBG.s"
	@echo "... Classes/MoreNeuronScene.o"
	@echo "... Classes/MoreNeuronScene.i"
	@echo "... Classes/MoreNeuronScene.s"
	@echo "... Classes/NeuronMenuScene.o"
	@echo "... Classes/NeuronMenuScene.i"
	@echo "... Classes/NeuronMenuScene.s"
	@echo "... Classes/PresentationScene.o"
	@echo "... Classes/PresentationScene.i"
	@echo "... Classes/PresentationScene.s"
	@echo "... Classes/TextInput.o"
	@echo "... Classes/TextInput.i"
	@echo "... Classes/TextInput.s"
	@echo "... proj.linux/main.o"
	@echo "... proj.linux/main.i"
	@echo "... proj.linux/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

